### ISSUE TITLE
darylldoyle/svg-sanitizer updates

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/FileValidatorSvgSanitizer#3]
There have been a few changes to the core library for PHP 8 support. From what I can tell, it's just about preventing a deprecation warning, so not critical, but still nice to have. 

![image](https://user-images.githubusercontent.com/871211/101389244-feacd200-3875-11eb-981e-b97d4aef4330.png)

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign

**Comment by adrianbj** [comment]
@ryancramerdesign - lots more important updates in the new 0.14.1 release:
https://github.com/darylldoyle/svg-sanitizer/releases

**Comment by ryancramerdesign** [comment]
@adrianbj I updated to 0.14.1 but there was only [one small change](https://github.com/ryancramerdesign/FileValidatorSvgSanitizer/commit/0db9955efba9c3b16c16659f9765643152eb4212), moving the location of the removeDoctype() method call. You mentioned a lot of important updates, so I'm not sure they are in 0.14.1? Maybe they are on an untagged version or on their develop branch?

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - perhaps "lots" was an exaggeration :)

That change did seem pretty important though as it prevent possible segmentation faults:
https://github.com/darylldoyle/svg-sanitizer/commit/61acf12fcbf77dda1bc93ece0df2d0d83440bde3
